### ISSUE TITLE
Error running pipeline on XL-100 box

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/pipeline-configs#135]
Hit this error when running the latest master on my test 100Mpc box:

```
Traceback (most recent call last):
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 2410, in parseImpl
    if (instring[loc] == self.firstMatchChar and
IndexError: string index out of range

During handling of the above exception, another exception occurred:

pyparsing.ParseException: Expected {snowflake | accent | symbol | c_over_c | function | group | frac | dfrac | stackrel | binom | genfrac | sqrt | overline | operatorname} (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/mathtext.py", line 2581, in parse
    result = self._expression.parseString(s)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3848, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/mathtext.py", line 2656, in math_string
    return self._math_expression.parseString(toks[0][1:-1])
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3848, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3848, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/cosma/local/Python/3.6.5/lib/python3.6/site-packages/pyparsing.py", line 3391, in parseImpl
    raise ParseSyntaxException._from_exception(pe)
pyparsing.ParseSyntaxException: Expected {snowflake | accent | symbol | c_over_c | function | group | frac | dfrac | stackrel | binom | genfrac | sqrt | overline | operatorname} (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eagle-xl/scripts/H2_mass_evolution.py", line 230, in <module>
    fig.savefig(f"{output_path}/H2_mass_evolution.png")
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 93, in print_figure
    super().print_figure(*args, **kwargs)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2126, in print_figure
    **kwargs)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 514, in print_png
    FigureCanvasAgg.draw(self)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 393, in draw
    self.figure.draw(self.renderer)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 1726, in draw
    self.execute_constrained_layout(renderer)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2446, in execute_constrained_layout
    do_constrained_layout(fig, renderer, h_pad, w_pad, hspace, wspace)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/_constrained_layout.py", line 168, in do_constrained_layout
    _make_layout_margins(ax, renderer, h_pad, w_pad)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/_constrained_layout.py", line 269, in _make_layout_margins
    tightbbox = ax.get_tightbbox(renderer=renderer)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 4327, in get_tightbbox
    bb_yaxis = self.yaxis.get_tightbbox(renderer)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/axis.py", line 1202, in get_tightbbox
    *ticklabelBoxes2,
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/axis.py", line 1200, in <genexpr>
    if a.get_visible()),
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/text.py", line 905, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/text.py", line 300, in _get_layout
    clean_line, self._fontproperties, ismath=ismath)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 209, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/mathtext.py", line 3354, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/matplotlib/mathtext.py", line 2586, in parse
    str(err)]))
ValueError: 
\rho_{\rm H
           ^
Expected {snowflake | accent | symbol | c_over_c | function | group | frac | dfrac | stackrel | binom | genfrac | sqrt | overline | operatorname} (at char 11), (line:1, col:12)
```

**Comment by MatthieuSchaller** [comment]
@JBorrow any quick thought? I am happy to dig from there.

**Comment by JBorrow** [comment]
Hmm, a very unhappy matplotlib. Looks like you have a user installed version, can you try revving?

**Comment by MatthieuSchaller** [comment]
Using the cosma system version worked. I am closing. Thanks.
