### ISSUE TITLE
Pipeline crashes if no data points are present in a plot

### ISSUE THREAD

**Issue by EvgeniiChaikin** [SWIFTSIM/pipeline-configs#23]
For a given plot, the pipeline will crash If there are no data in the arrays whose units` unyt` is trying to convert or use. This is especially true for small boxes.

See an example of the crash below.

_Suggestion_:  can we catch `UnitConversionError` and produce an empty plot?

```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Creating figures:  33%|█████████████████████████████████████████████████▋                                                                                                   | 20/60 [00:16<00:33,  1.20it/s]Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "/home/evgenii/anaconda3/bin/swift-pipeline", line 207, in <module>
    directory=args.output, file_extension=PLOT_FILE_EXTENSION, debug=args.debug
  File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/objects.py", line 969, in create_plots
    file_extension=file_extension,
  File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/objects.py", line 808, in make_plot
    fig, ax = getattr(self, f"_make_plot_{self.plot_type}")(catalogue=catalogue)
  File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/objects.py", line 713, in _make_plot_scatter
    self._add_lines_to_axes(ax=ax, x=x, y=y)
  File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/objects.py", line 653, in _add_lines_to_axes
    self.median_line.plot_line(ax=ax, x=x, y=y, label="Median")
  File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/lines.py", line 338, in plot_line
    linewidth=0.0,
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5048, in fill_between
    y1 = ma.masked_invalid(self.convert_yunits(y1))
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 195, in convert_yunits
    return ax.yaxis.convert_units(y)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py", line 1530, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/unyt/mpl_interface.py", line 143, in convert
    converted_value = value.to(*unit)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/unyt/array.py", line 881, in to
    return self.in_units(units, equivalence=equivalence, **kwargs)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/unyt/array.py", line 809, in in_units
    new_units, self.dtype
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/unyt/unit_object.py", line 687, in get_conversion_factor
    return _get_conversion_factor(self, other_units, dtype)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/unyt/unit_object.py", line 933, in _get_conversion_factor
    old_units, old_units.dimensions, new_units, new_units.dimensions
unyt.exceptions.UnitConversionError: Cannot convert between 'dimensionless' (dim '1') and '1/Gyr' (dim '1/(time)').
```

**Comment by JBorrow** [comment]
This should be fixed with my change to unyt, but it will take some time to propagate.

**Comment by EvgeniiChaikin** [comment]
I am closing this issue because pipeline no longer crashes if there are no data points
